"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Provider";
import AppBar from "@/components/AppBar";
import BottomTabs from "@/components/BottomNavigation";
import SplashScreen from "@/components/SplashScreen";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "MyNextPWA",
//   description: "Generated by create next app",
//   manifest: "/manifest.json",
//   icons: {
//     apple: "/ican.png",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100%" }}>
        {isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} />
        ) : (
          <Providers>
            <AppBar />
            {children}
            <BottomTabs />
          </Providers>
        )}
      </body>
    </html>
  );
}
