import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IntermediatoryPage from "./intermediatory";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyNextPWA",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    apple: "/ican.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <IntermediatoryPage>{children}</IntermediatoryPage>
      </body>
    </html>
  );
}
